# Generated by Django 5.2.6 on 2025-11-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="duration",
            field=models.PositiveIntegerField(
                default=20, help_text="Duration in minutes"
            ),
        ),
    ]
