# Generated by Django 5.2.6 on 2025-11-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_quiz_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="total_marks",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
