# Generated by Django 5.2.6 on 2025-10-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="progress",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
