# Generated by Django 5.2.6 on 2025-11-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_enrollment_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
