# Generated by Django 5.2.6 on 2025-11-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_course_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="instructor",
            new_name="owner",
        ),
    ]
